### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Cwpapi' not found in...

### ISSUE THREAD

**Issue by tomasnorth** [puerari/cwp_api#2]
Currently facing a problem whilst trying to use the API via this wrapper.

My Code:
```
<?php
require_once 'vendor/autoload.php';
$cwpApi = new Cwpapi('http://myip', 'apikey');
$status = $cwpApi->createAccount('test.co', 'test1234', 'userPassword', 'hello@test.co', 'myip');
if ((json_decode($status))->status != 'OK') {
    exit((json_decode($status))->msj);
}

?>
```

Obviously the information is all filled correctly.

Error:
`Fatal error: Uncaught Error: Class 'Cwpapi' not found in C:\xampp\htdocs\cwpplugin\index.php:3 Stack trace: #0 {main} thrown in C:\xampp\htdocs\cwpplugin\index.php on line 3`

Looking to use the API for a project. Seems to be the only recent one (that I hoped worked)

**Comment by namenodeis** [comment]
I have not used this, but I follow this project. Have you tried giving the full path to 'vendor/autoload.php' line?

**Comment by tomasnorth** [comment]
I have not, I'll give that a spin and see where it goes

**Comment by tomasnorth** [comment]
Nope, that doesn't seem to make a difference

**Comment by puerari** [comment]
Hello!

Try to use:
use Puerari\Cwp\Cwpapi;

**Comment by tomasnorth** [comment]
Hi Leandro,

This was something I was trying months ago - unfortunate it didn't catch your eye sooner ahaha.

Currently I've moved away from CWP as I was going to code a custom client area for email hosting and use CWP as the backend.

Although, if I come back to this in the future - I'll try that.

Thanks for your awesome work :D
